### ISSUE TITLE
 Uncaught ArgumentCountError: array_merge() 

### ISSUE THREAD

**Issue by Jawn78** [shlinkio/shlink#1074]
When I run composer install I get the below error. 

PHP Fatal error:  Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php:84

I have 
php
```
PHP 8.0.3 (cli) (built: Mar  5 2021 07:53:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies
```

Composer:
```
Running 1.6.3 (2018-01-31 16:28:17) with PHP 8.0.3 on Linux / 4.15.0-140-generic
Composer - Package Management for PHP
```

```
PHP Fatal error:  Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php:84
Stack trace:
#0 [internal function]: array_merge()
#1 /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array()
#2 /usr/share/php/Composer/DependencyResolver/Solver.php(383): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages()
#3 /usr/share/php/Composer/DependencyResolver/Solver.php(736): Composer\DependencyResolver\Solver->selectAndInstall()
#4 /usr/share/php/Composer/DependencyResolver/Solver.php(228): Composer\DependencyResolver\Solver->runSat()
#5 /usr/share/php/Composer/Installer.php(473): Composer\DependencyResolver\Solver->solve()
#6 /usr/share/php/Composer/Installer.php(227): Composer\Installer->doInstall()
#7 /usr/share/php/Composer/Command/InstallCommand.php(119): Composer\Installer->run()
#8 /usr/share/php/Symfony/Component/Console/Command/Command.php(252): Composer\Command\InstallCommand->execute()
#9 /usr/share/php/Symfony/Component/Console/Application.php(946): Symfony\Component\Console\Command\Command->run()
#10 /usr/share/php/Symfony/Component/Console/Application.php(248): Symfony\Component\Console\Application->doRunCommand()
#11 /usr/share/php/Composer/Console/Application.php(251): Symfony\Component\Console\Application->doRun()
#12 /usr/share/php/Symfony/Component/Console/Application.php(148): Composer\Console\Application->doRun()
#13 /usr/share/php/Composer/Console/Application.php(100): Symfony\Component\Console\Application->run()
#14 /usr/bin/composer(59): Composer\Console\Application->run()
#15 {main}
  thrown in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php on line 84

Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php:84
Stack trace:
#0 [internal function]: array_merge()
#1 /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array()
#2 /usr/share/php/Composer/DependencyResolver/Solver.php(383): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages()
#3 /usr/share/php/Composer/DependencyResolver/Solver.php(736): Composer\DependencyResolver\Solver->selectAndInstall()
#4 /usr/share/php/Composer/DependencyResolver/Solver.php(228): Composer\DependencyResolver\Solver->runSat()
#5 /usr/share/php/Composer/Installer.php(473): Composer\DependencyResolver\Solver->solve()
#6 /usr/share/php/Composer/Installer.php(227): Composer\Installer->doInstall()
#7 /usr/share/php/Composer/Command/InstallCommand.php(119): Composer\Installer->run()
#8 /usr/share/php/Symfony/Component/Console/Command/Command.php(252): Composer\Command\InstallCommand->execute()
#9 /usr/share/php/Symfony/Component/Console/Application.php(946): Symfony\Component\Console\Command\Command->run()
#10 /usr/share/php/Symfony/Component/Console/Application.php(248): Symfony\Component\Console\Application->doRunCommand()
#11 /usr/share/php/Composer/Console/Application.php(251): Symfony\Component\Console\Application->doRun()
#12 /usr/share/php/Symfony/Component/Console/Application.php(148): Composer\Console\Application->doRun()
#13 /usr/share/php/Composer/Console/Application.php(100): Symfony\Component\Console\Application->run()
#14 /usr/bin/composer(59): Composer\Console\Application->run()
#15 {main}
  thrown in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php on line 84
```

**Comment by acelaya** [comment]
Probably related with this https://github.com/composer/composer/issues/9097

**Comment by gnonegue** [comment]
I was experiencing the following issue:

PHP message: PHP Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /(…)/wp-content/plugins/twentig/inc/theme-tools/customizer-functions.php:84

This fixed it:

```
- $choices = call_user_func_array( 'array_merge', $choices );
+ $choices = call_user_func_array( 'array_merge', array_values($choices) );
```
