### ISSUE TITLE
Installer errors out with --no-interaction flag

### ISSUE THREAD

**Issue by dphiffer** [shlinkio/shlink#1446]
#### How Shlink is set-up

* Shlink Version: 3.1.1
* PHP Version: 8.1.6
* How do you serve Shlink: Self-hosted Apache
* Database engine used: MariaDB 10.2.41

#### Summary

1. Download and unzip shlink3.1.1_php8.1_dist.zip
2. Set environment vars (`DEFAULT_DOMAIN`, `IS_HTTPS_ENABLED`, `PORT`, `DB_DRIVER`, `DB_NAME`, `DB_USER`, `DB_PASSWORD`, `DB_HOST`, `DB_PORT`)
3. Run `vendor/bin/shlink-installer install --no-interaction`

#### Current behavior

```
$ vendor/bin/shlink-installer install --no-interaction

 Welcome to Shlink!!
 This tool will guide you through the installation process.

DATABASE
========

[16-May-2022 21:30:00 UTC] PHP Fatal error:  Uncaught TypeError: Shlinkio\Shlink\Installer\Config\Option\Database\DatabaseUserConfigOption::askRequired(): Return value must be of type string, null returned in /var/www/shlink/vendor/shlinkio/shlink-installer/src/Util/AskUtilsTrait.php:20
Stack trace:
#0 /var/www/shlink/vendor/shlinkio/shlink-installer/src/Config/Option/Database/DatabaseUserConfigOption.php(27): Shlinkio\Shlink\Installer\Config\Option\Database\DatabaseUserConfigOption->askRequired(Object(Symfony\Component\Console\Style\SymfonyStyle), 'username', 'Database userna...')
#1 /var/www/shlink/vendor/shlinkio/shlink-installer/src/Config/ConfigGenerator.php(50): Shlinkio\Shlink\Installer\Config\Option\Database\DatabaseUserConfigOption->ask(Object(Symfony\Component\Console\Style\SymfonyStyle), Object(Shlinkio\Shlink\Config\Collection\PathCollection))
#2 /var/www/shlink/vendor/shlinkio/shlink-installer/src/Command/AbstractInstallCommand.php(49): Shlinkio\Shlink\Installer\Config\ConfigGenerator->generateConfigInteractively(Object(Symfony\Component\Console\Style\SymfonyStyle), Array)
#3 /var/www/shlink/vendor/symfony/console/Command/Command.php(291): Shlinkio\Shlink\Installer\Command\AbstractInstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/shlink/vendor/symfony/console/Application.php(989): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/shlink/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Shlinkio\Shlink\Installer\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/shlink/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/shlink/vendor/shlinkio/shlink-installer/bin/shlink-installer(13): Symfony\Component\Console\Application->run()
#8 /var/www/shlink/vendor/bin/shlink-installer(117): include('/var/www/shlink...')
#9 {main}
  thrown in /var/www/shlink/vendor/shlinkio/shlink-installer/src/Util/AskUtilsTrait.php on line 20
```

#### Expected behavior

I expected the installation to complete.

#### How to reproduce

Here is the Dockerfile that builds the server (my goal is to get Shlink running on the same server that runs WordPress):

```
FROM wordpress:php8.1

RUN apt update && \
	apt install unzip

RUN cd /var/www && \
	curl -sL -o shlink.zip https://github.com/shlinkio/shlink/releases/download/v3.1.1/shlink3.1.1_php8.1_dist.zip && \
	unzip shlink.zip && \
	unzip shlink3.1.1_php8.1_dist.zip && \
	mv shlink3.1.1_php8.1_dist shlink && \
	rm *.zip

RUN docker-php-ext-install pdo_mysql

COPY shlinkpress.conf /etc/apache2/sites-available/shlinkpress.conf
RUN a2ensite shlinkpress.conf
```

And then: `docker compose exec web /var/www/shlink/vendor/bin/shlink-installer install --no-interaction`

**Comment by dphiffer** [comment]
In case it's helpful, here is what I get from running `./vendor/bin/shlink-installer install -vvv`:

```
Initializing database... [Running "/usr/local/bin/php bin/cli db:create"]   RUN  '/usr/local/bin/php' 'bin/cli' 'db:create'
  OUT  
  OUT   [OK] Database already exists. Run "db:migrate" command to make sure it is up to
  OUT        date.                                                                     
  OUT  
  OUT  
  RES  Command ran successfully
 Success!
Updating database... [Running "/usr/local/bin/php bin/cli db:migrate"]   RUN  '/usr/local/bin/php' 'bin/cli' 'db:migrate'
  OUT  Migrating database...
  OUT  
  ERR    RUN  '/usr/local/bin/php' 'vendor/doctrine/migrations/bin/doctrine-migrations.php' 'migrations:migrate' '--no-interaction'
  ERR    ERR  
  ERR    ERR  In SchemaException.php line 35:
  ERR    ERR                                                                         
  ERR    ERR    [Doctrine\DBAL\Schema\SchemaException (10)]                          
  ERR    ERR    There is no table with name 'shlinkpress.short_urls' in the schema.  
  ERR    ERR                                                                         
  ERR    ERR  
  ERR    ERR  Exception trace:
  ERR    ERR    at /var/www/shlink/vendor/doctrine/dbal/src/Schema/SchemaException.php:35
  ERR    ERR   Doctrine\DBAL\Schema\SchemaException::tableDoesNotExist() at /var/www/shlink/vendor/doctrine/dbal/src/Schema/Schema.php:189
  ERR    ERR   Doctrine\DBAL\Schema\Schema->getTable() at /var/www/shlink/vendor/friendsofphp/proxy-manager-lts/src/ProxyManager/GeneratorStrategy/EvaluatingGeneratorStrategy.php(54) : eval()'d code:49
  ERR    ERR   ProxyManagerGeneratedProxy\__PM__\Doctrine\DBAL\Schema\Schema\Generated0e88da61ef53e35256c1c89a3ab6954e->getTable() at /var/www/shlink/vendor/friendsofphp/proxy-manager-lts/src/ProxyManager/GeneratorStrategy/EvaluatingGeneratorStrategy.php(54) : eval()'d code:49
  ERR    ERR   ProxyManagerGeneratedProxy\__PM__\Doctrine\DBAL\Schema\Schema\Generated0e88da61ef53e35256c1c89a3ab6954e->getTable() at /var/www/shlink/data/migrations/Version20160819142757.php:28
  ERR    ERR   ShlinkMigrations\Version20160819142757->up() at /var/www/shlink/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:160
  ERR    ERR   Doctrine\Migrations\Version\DbalExecutor->executeMigration() at /var/www/shlink/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:95
  ERR    ERR   Doctrine\Migrations\Version\DbalExecutor->execute() at /var/www/shlink/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:107
  ERR    ERR   Doctrine\Migrations\DbalMigrator->executePlan() at /var/www/shlink/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:71
  ERR    ERR   Doctrine\Migrations\DbalMigrator->executeMigrations() at /var/www/shlink/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:157
  ERR    ERR   Doctrine\Migrations\DbalMigrator->migrate() at /var/www/shlink/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php:210
  ERR    ERR   Doctrine\Migrations\Tools\Console\Command\MigrateCommand->execute() at /var/www/shlink/vendor/symfony/console/Command/Command.php:291
  ERR    ERR   Symfony\Component\Console\Command\Command->run() at /var/www/shlink/vendor/symfony/console/Application.php:989
  ERR    ERR   Symfony\Component\Console\Application->doRunCommand() at /var/www/shlink/vendor/symfony/console/Application.php:299
  ERR    ERR   Symfony\Component\Console\Application->doRun() at /var/www/shlink/vendor/symfony/console/Application.php:171
  ERR    ERR   Symfony\Component\Console\Application->run() at /var/www/shlink/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/ConsoleRunner.php:95
  ERR    ERR   Doctrine\Migrations\Tools\Console\ConsoleRunner::run() at /var/www/shlink/vendor/doctrine/migrations/bin/doctrine-migrations.php:45
  ERR    ERR   Doctrine\Migrations\{closure}() at /var/www/shlink/vendor/doctrine/migrations/bin/doctrine-migrations.php:46
  ERR    ERR  
  ERR    ERR  migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] [<version>]
  ERR    ERR  
  ERR    ERR  
  ERR  In Process.php line 267:
  ERR                                                                                 
  ERR    [Symfony\Component\Process\Exception\ProcessFailedException]                 
  ERR    The command "'/usr/local/bin/php' 'vendor/doctrine/migrations/bin/doctrine-  
  ERR    migrations.php' 'migrations:migrate' '--no-interaction'" failed.             
  ERR                                                                                 
  ERR    Exit Code: 10(Unknown error)                                                 
  ERR                                                                                 
  ERR    Working directory: /var/www/shlink                                           
  ERR                                                                                 
  ERR    Output:                                                                      
  ERR    ================                                                             
  ERR                                                                                 
  ERR                                                                                 
  ERR    Error Output:                                                                
  ERR    ================                                                             
  ERR                                                                                 
  ERR    In SchemaException.php line 35:                                              
  ERR                                                                                 
  ERR      [Doctrine\DBAL\Schema\SchemaException (10)]                                
  ERR      There is no table with name 'shlinkpress.short_urls' in the schema.        
  ERR                                                                                 
  ERR                                                                                 
  ERR    Exception trace:                                                             
  ERR      at /var/www/shlink/vendor/doctrine/dbal/src/Schema/SchemaException.php:35  
  ERR     Doctrine\DBAL\Schema\SchemaException::tableDoesNotExist() at /var/www/shli  
  ERR    nk/vendor/doctrine/dbal/src/Schema/Schema.php:189                            
  ERR     Doctrine\DBAL\Schema\Schema->getTable() at /var/www/shlink/vendor/friendso  
  ERR    fphp/proxy-manager-lts/src/ProxyManager/GeneratorStrategy/EvaluatingGenerat  
  ERR    orStrategy.php(54) : eval()'d code:49                                        
  ERR     ProxyManagerGeneratedProxy\__PM__\Doctrine\DBAL\Schema\Schema\Generated0e8  
  ERR    8da61ef53e35256c1c89a3ab6954e->getTable() at /var/www/shlink/vendor/friends  
  ERR    ofphp/proxy-manager-lts/src/ProxyManager/GeneratorStrategy/EvaluatingGenera  
  ERR    torStrategy.php(54) : eval()'d code:49                                       
  ERR     ProxyManagerGeneratedProxy\__PM__\Doctrine\DBAL\Schema\Schema\Generated0e8  
  ERR    8da61ef53e35256c1c89a3ab6954e->getTable() at /var/www/shlink/data/migration  
  ERR    s/Version20160819142757.php:28                                               
  ERR     ShlinkMigrations\Version20160819142757->up() at /var/www/shlink/vendor/doc  
  ERR    trine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:160        
  ERR     Doctrine\Migrations\Version\DbalExecutor->executeMigration() at /var/www/s  
  ERR    hlink/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecut  
  ERR    or.php:95                                                                    
  ERR     Doctrine\Migrations\Version\DbalExecutor->execute() at /var/www/shlink/ven  
  ERR    dor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:107         
  ERR     Doctrine\Migrations\DbalMigrator->executePlan() at /var/www/shlink/vendor/  
  ERR    doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:71              
  ERR     Doctrine\Migrations\DbalMigrator->executeMigrations() at /var/www/shlink/v  
  ERR    endor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:157       
  ERR     Doctrine\Migrations\DbalMigrator->migrate() at /var/www/shlink/vendor/doct  
  ERR    rine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/MigrateComman  
  ERR    d.php:210                                                                    
  ERR     Doctrine\Migrations\Tools\Console\Command\MigrateCommand->execute() at /va  
  ERR    r/www/shlink/vendor/symfony/console/Command/Command.php:291                  
  ERR     Symfony\Component\Console\Command\Command->run() at /var/www/shlink/vendor  
  ERR    /symfony/console/Application.php:989                                         
  ERR     Symfony\Component\Console\Application->doRunCommand() at /var/www/shlink/v  
  ERR    endor/symfony/console/Application.php:299                                    
  ERR     Symfony\Component\Console\Application->doRun() at /var/www/shlink/vendor/s  
  ERR    ymfony/console/Application.php:171                                           
  ERR     Symfony\Component\Console\Application->run() at /var/www/shlink/vendor/doc  
  ERR    trine/migrations/lib/Doctrine/Migrations/Tools/Console/ConsoleRunner.php:95  
  ERR     Doctrine\Migrations\Tools\Console\ConsoleRunner::run() at /var/www/shlink/  
  ERR    vendor/doctrine/migrations/bin/doctrine-migrations.php:45                    
  ERR     Doctrine\Migrations\{closure}() at /var/www/shlink/vendor/doctrine/migrati  
  ERR    ons/bin/doctrine-migrations.php:46                                           
  ERR                                                                                 
  ERR    migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--  
  ERR    allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CO  
  ERR    NFIGURATION] [--em EM] [--conn CONN] [--] [<version>]                        
  ERR                                                                                 
  ERR  
  ERR  Exception trace:
  ERR    at /var/www/shlink/vendor/symfony/process/Process.php:267
  ERR   Symfony\Component\Process\Process->mustRun() at /var/www/shlink/module/CLI/src/Util/ProcessRunner.php:48
  ERR   Shlinkio\Shlink\CLI\Util\ProcessRunner->run() at /var/www/shlink/module/CLI/src/Command/Db/AbstractDatabaseCommand.php:30
  ERR   Shlinkio\Shlink\CLI\Command\Db\AbstractDatabaseCommand->runPhpCommand() at /var/www/shlink/module/CLI/src/Command/Db/MigrateDatabaseCommand.php:31
  ERR   Shlinkio\Shlink\CLI\Command\Db\MigrateDatabaseCommand->lockedExecute() at /var/www/shlink/module/CLI/src/Command/Util/AbstractLockedCommand.php:35
  ERR   Shlinkio\Shlink\CLI\Command\Util\AbstractLockedCommand->execute() at /var/www/shlink/vendor/symfony/console/Command/Command.php:291
  ERR   Symfony\Component\Console\Command\Command->run() at /var/www/shlink/vendor/symfony/console/Application.php:989
  ERR   Symfony\Component\Console\Application->doRunCommand() at /var/www/shlink/vendor/symfony/console/Application.php:299
  ERR   Symfony\Component\Console\Application->doRun() at /var/www/shlink/vendor/symfony/console/Application.php:171
  ERR   Symfony\Component\Console\Application->run() at /var/www/shlink/bin/cli:10
  ERR  
  ERR  db:migrate
  ERR  
  ERR  
  RES  1 Command did not run successfully
```
