### ISSUE TITLE
Randomly happening PDOException: SQLSTATE[HY000]: General error: 7 server closed the connection unexpectedly

### ISSUE THREAD

**Issue by panki** [shlinkio/shlink#1630]
#### How Shlink is set-up

* Shlink Version: stable (3.3.2)
* PHP Version: x.y.z
* How do you serve Shlink: Docker container created from official dockerhub image (tag: stable) 
* Database engine used: PostgreSQL 14.2 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit also running in docker

#### Summary

Everything works well, but periodically I receive 500 error, the same also happens on production with the same shlink version and PostgreSQL 11.16, compiled by Visual C++ build 1800, 64-bit.

No other services experience any problems with postgres, I'm 100% sure it doesn't drop connections.

Shlink container logs:

```
local-dev-url-shortener-1  | [2022-12-15T18:11:44.081153+00:00] [94490011-9de4-4e8e-8284-cf9afb7a408d] Access.ERROR - - "POST /rest/v3/short-urls HTTP/1.1" 500 143
local-dev-url-shortener-1  | [2022-12-15T18:11:45.548765+00:00] [77b546b8-86ef-4e67-865c-307168ad2894] Shlink.ERROR - PDOException: SQLSTATE[HY000]: General error: 7 server closed the connection unexpectedly
local-dev-url-shortener-1  | 	This probably means the server terminated abnormally
local-dev-url-shortener-1  | 	before or while processing the request. in /etc/shlink/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:134
local-dev-url-shortener-1  | Stack trace:
local-dev-url-shortener-1  | #0 /etc/shlink/vendor/doctrine/dbal/src/Driver/PDO/Statement.php(134): PDOStatement->execute(NULL)
local-dev-url-shortener-1  | #1 /etc/shlink/vendor/doctrine/dbal/src/Connection.php(1063): Doctrine\DBAL\Driver\PDO\Statement->execute()
local-dev-url-shortener-1  | #2 /etc/shlink/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(750): Doctrine\DBAL\Connection->executeQuery('SELECT t0.id AS...', Array, Array)
local-dev-url-shortener-1  | #3 /etc/shlink/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(241): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load(Array, NULL, NULL, Array, NULL, 1, NULL)
local-dev-url-shortener-1  | #4 /etc/shlink/module/Rest/src/Service/ApiKeyService.php(85): Doctrine\ORM\EntityRepository->findOneBy(Array)
local-dev-url-shortener-1  | #5 /etc/shlink/module/Rest/src/Service/ApiKeyService.php(52): Shlinkio\Shlink\Rest\Service\ApiKeyService->getByKey('test-api-key')
local-dev-url-shortener-1  | #6 /etc/shlink/module/Rest/src/Middleware/AuthenticationMiddleware.php(47): Shlinkio\Shlink\Rest\Service\ApiKeyService->check('test-api-key')
local-dev-url-shortener-1  | #7 /etc/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(27): Shlinkio\Shlink\Rest\Middleware\AuthenticationMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #8 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #9 /etc/shlink/module/Rest/src/Middleware/BodyParserMiddleware.php(35): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #10 /etc/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(27): Shlinkio\Shlink\Rest\Middleware\BodyParserMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #11 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #12 /etc/shlink/vendor/mezzio/mezzio-router/src/Middleware/ImplicitOptionsMiddleware.php(72): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #13 /etc/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(27): Mezzio\Router\Middleware\ImplicitOptionsMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #14 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #15 /etc/shlink/module/Rest/src/Middleware/ErrorHandler/BackwardsCompatibleProblemDetailsHandler.php(22): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #16 /etc/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(27): Shlinkio\Shlink\Rest\Middleware\ErrorHandler\BackwardsCompatibleProblemDetailsHandler->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #17 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #18 /etc/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #19 /etc/shlink/vendor/laminas/laminas-stratigility/src/Middleware/PathMiddlewareDecorator.php(60): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
local-dev-url-shortener-1  | #20 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Laminas\Stratigility\Middleware\PathMiddlewareDecorator->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #21 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(42): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #22 /etc/shlink/vendor/mezzio/mezzio-router/src/Middleware/ImplicitHeadMiddleware.php(76): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #23 /etc/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(27): Mezzio\Router\Middleware\ImplicitHeadMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #24 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #25 /etc/shlink/vendor/mezzio/mezzio-router/src/Middleware/RouteMiddleware.php(50): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #26 /etc/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(27): Mezzio\Router\Middleware\RouteMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #27 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #28 /etc/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #29 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #30 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(42): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #31 /etc/shlink/vendor/shlinkio/shlink-common/src/Middleware/CloseDbConnectionMiddleware.php(24): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #32 /etc/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(27): Shlinkio\Shlink\Common\Middleware\CloseDbConnectionMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #33 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #34 /etc/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #35 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #36 /etc/shlink/vendor/laminas/laminas-stratigility/src/Middleware/PathMiddlewareDecorator.php(122): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #37 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(42): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #38 /etc/shlink/vendor/mezzio/mezzio-problem-details/src/ProblemDetailsMiddleware.php(47): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #39 /etc/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(27): Mezzio\ProblemDetails\ProblemDetailsMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #40 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #41 /etc/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #42 /etc/shlink/vendor/laminas/laminas-stratigility/src/Middleware/PathMiddlewareDecorator.php(60): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
local-dev-url-shortener-1  | #43 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Laminas\Stratigility\Middleware\PathMiddlewareDecorator->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #44 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(42): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #45 /etc/shlink/module/Rest/src/Middleware/CrossDomainMiddleware.php(24): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #46 /etc/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(27): Shlinkio\Shlink\Rest\Middleware\CrossDomainMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #47 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #48 /etc/shlink/vendor/laminas/laminas-stratigility/src/Middleware/ErrorHandler.php(129): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #49 /etc/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(27): Laminas\Stratigility\Middleware\ErrorHandler->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #50 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #51 /etc/shlink/vendor/php-middleware/request-id/src/RequestIdMiddleware.php(32): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #52 /etc/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(27): PhpMiddleware\RequestId\RequestIdMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #53 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #54 /etc/shlink/vendor/shlinkio/shlink-common/src/Middleware/ContentLengthMiddleware.php(24): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #55 /etc/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(27): Shlinkio\Shlink\Common\Middleware\ContentLengthMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #56 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #57 /etc/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #58 /etc/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
local-dev-url-shortener-1  | #59 /etc/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #60 /etc/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(64): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\EmptyPipelineHandler))
local-dev-url-shortener-1  | #61 /etc/shlink/vendor/mezzio/mezzio-swoole/src/Event/RequestHandlerRequestListener.php(109): Laminas\Stratigility\MiddlewarePipe->handle(Object(Laminas\Diactoros\ServerRequest))
local-dev-url-shortener-1  | #62 /etc/shlink/vendor/mezzio/mezzio-swoole/src/Event/EventDispatcher.php(36): Mezzio\Swoole\Event\RequestHandlerRequestListener->__invoke(Object(Mezzio\Swoole\Event\RequestEvent))
local-dev-url-shortener-1  | #63 /etc/shlink/vendor/mezzio/mezzio-swoole/src/SwooleRequestHandlerRunner.php(147): Mezzio\Swoole\Event\EventDispatcher->dispatch(Object(Mezzio\Swoole\Event\RequestEvent))
local-dev-url-shortener-1  | #64 [internal function]: Mezzio\Swoole\SwooleRequestHandlerRunner->onRequest(Object(Swoole\Http\Request), Object(Swoole\Http\Response))
local-dev-url-shortener-1  | #65 {main}
```

**Comment by panki** [comment]
Configuration used to run the service:
```
      DEFAULT_DOMAIN: example.com
      IS_HTTPS_ENABLED: "false"
      GEOLITE_LICENSE_KEY:
      DEFAULT_SHORT_CODES_LENGTH: 6
      PORT: 8881
      WEB_WORKER_NUM: 4
      TASK_WORKER_NUM: 4
      INITIAL_API_KEY: test-api-key
      DB_DRIVER: postgres
      DB_NAME: shlink
      DB_USER: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DISABLE_TRACKING: "true"
      DISABLE_IP_TRACKING: "true"
      DISABLE_REFERRER_TRACKING: "true"
      DISABLE_UA_TRACKING: "true"
      ANONYMIZE_REMOTE_ADDR: "true"
      SKIP_INITIAL_GEOLITE_DOWNLOAD: "true"
```

**Comment by panki** [comment]
Also have tried to use the `latest` vesrion, the same problem.
