### ISSUE TITLE
Shlink.ERROR - Error: Typed property Shlinkio\Shlink\Core\ShortUrl\Entity\ShortUrl::$deviceLongUrls must not be accessed before initialization in /var/www/shlink/module/Core/src/ShortUrl/Entity/ShortUrl.php:338

### ISSUE THREAD

**Issue by theofficialgman** [shlinkio/shlink#2187]
### Shlink version

3.5.0/3.5.4/3.6.4

### PHP version

8.1.29

### How do you serve Shlink

Self-hosted nginx

### Database engine

MySQL

### Database version

8.0.39

### Current behavior

Many rest API enpoints fail.

One such enpoint is the shortcode enpoint where the following log is created in `data/log/`
```
[2024-09-03T18:18:02.327422+00:00] [8fa44249-2d70-437a-a564-b7de3e7cac97] Shlink.ERROR - Error: Typed property Shlinkio\Shlink\Core\ShortUrl\Entity\ShortUrl::$deviceLongUrls must not be accessed before initialization in /var/www/shlink/module/Core/src/ShortUrl/Entity/ShortUrl.php:338
Stack trace:
#0 /var/www/shlink/module/Core/src/ShortUrl/Transformer/ShortUrlDataTransformer.php(30): Shlinkio\Shlink\Core\ShortUrl\Entity\ShortUrl->deviceLongUrls()
#1 [internal function]: Shlinkio\Shlink\Core\ShortUrl\Transformer\ShortUrlDataTransformer->transform()
#2 /var/www/shlink/vendor/shlinkio/shlink-common/src/Paginator/Util/PagerfantaUtilsTrait.php(38): array_map()
#3 /var/www/shlink/vendor/shlinkio/shlink-common/src/Paginator/Util/PagerfantaUtilsTrait.php(25): Shlinkio\Shlink\Rest\Action\ShortUrl\ListShortUrlsAction->serializeItems()
#4 /var/www/shlink/module/Rest/src/Action/ShortUrl/ListShortUrlsAction.php(36): Shlinkio\Shlink\Rest\Action\ShortUrl\ListShortUrlsAction->serializePaginator()
#5 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Middleware/RequestHandlerMiddleware.php(46): Shlinkio\Shlink\Rest\Action\ShortUrl\ListShortUrlsAction->handle()
#6 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Laminas\Stratigility\Middleware\RequestHandlerMiddleware->process()
#7 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process()
#8 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#9 /var/www/shlink/vendor/mezzio/mezzio-router/src/Route.php(79): Laminas\Stratigility\MiddlewarePipe->process()
#10 /var/www/shlink/vendor/mezzio/mezzio-router/src/RouteResult.php(109): Mezzio\Router\Route->process()
#11 /var/www/shlink/vendor/mezzio/mezzio-router/src/Middleware/DispatchMiddleware.php(32): Mezzio\Router\RouteResult->process()
#12 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Mezzio\Router\Middleware\DispatchMiddleware->process()
#13 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process()
#14 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#15 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Laminas\Stratigility\MiddlewarePipe->process()
#16 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Middleware/PathMiddlewareDecorator.php(122): Laminas\Stratigility\Next->handle()
#17 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(42): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#18 /var/www/shlink/module/Rest/src/Middleware/AuthenticationMiddleware.php(52): Laminas\Stratigility\Next->handle()
#19 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Shlinkio\Shlink\Rest\Middleware\AuthenticationMiddleware->process()
#20 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process()
#21 /var/www/shlink/module/Rest/src/Middleware/BodyParserMiddleware.php(34): Laminas\Stratigility\Next->handle()
#22 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Shlinkio\Shlink\Rest\Middleware\BodyParserMiddleware->process()
#23 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process()
#24 /var/www/shlink/vendor/mezzio/mezzio-router/src/Middleware/ImplicitOptionsMiddleware.php(75): Laminas\Stratigility\Next->handle()
#25 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Mezzio\Router\Middleware\ImplicitOptionsMiddleware->process()
#26 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process()
#27 /var/www/shlink/module/Rest/src/Middleware/ErrorHandler/BackwardsCompatibleProblemDetailsHandler.php(22): Laminas\Stratigility\Next->handle()
#28 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Shlinkio\Shlink\Rest\Middleware\ErrorHandler\BackwardsCompatibleProblemDetailsHandler->process()
#29 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process()
#30 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#31 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Middleware/PathMiddlewareDecorator.php(62): Laminas\Stratigility\MiddlewarePipe->process()
#32 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Laminas\Stratigility\Middleware\PathMiddlewareDecorator->process()
#33 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(42): Laminas\Stratigility\Next->handle()
#34 /var/www/shlink/vendor/mezzio/mezzio-router/src/Middleware/ImplicitHeadMiddleware.php(77): Laminas\Stratigility\Next->handle()
#35 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Mezzio\Router\Middleware\ImplicitHeadMiddleware->process()
#36 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process()
#37 /var/www/shlink/vendor/mezzio/mezzio-router/src/Middleware/RouteMiddleware.php(50): Laminas\Stratigility\Next->handle()
#38 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Mezzio\Router\Middleware\RouteMiddleware->process()
#39 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process()
#40 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#41 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Laminas\Stratigility\MiddlewarePipe->process()
#42 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(42): Laminas\Stratigility\Next->handle()
#43 /var/www/shlink/vendor/shlinkio/shlink-common/src/Middleware/CloseDbConnectionMiddleware.php(24): Laminas\Stratigility\Next->handle()
#44 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Shlinkio\Shlink\Common\Middleware\CloseDbConnectionMiddleware->process()
#45 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process()
#46 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#47 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Laminas\Stratigility\MiddlewarePipe->process()
#48 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Middleware/PathMiddlewareDecorator.php(122): Laminas\Stratigility\Next->handle()
#49 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(42): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#50 /var/www/shlink/vendor/mezzio/mezzio-problem-details/src/ProblemDetailsMiddleware.php(46): Laminas\Stratigility\Next->handle()
#51 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Mezzio\ProblemDetails\ProblemDetailsMiddleware->process()
#52 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process()
#53 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#54 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Middleware/PathMiddlewareDecorator.php(62): Laminas\Stratigility\MiddlewarePipe->process()
#55 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Laminas\Stratigility\Middleware\PathMiddlewareDecorator->process()
#56 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(42): Laminas\Stratigility\Next->handle()
#57 /var/www/shlink/module/Rest/src/Middleware/CrossDomainMiddleware.php(24): Laminas\Stratigility\Next->handle()
#58 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Shlinkio\Shlink\Rest\Middleware\CrossDomainMiddleware->process()
#59 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process()
#60 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Middleware/ErrorHandler.php(129): Laminas\Stratigility\Next->handle()
#61 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Laminas\Stratigility\Middleware\ErrorHandler->process()
#62 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process()
#63 /var/www/shlink/vendor/php-middleware/request-id/src/RequestIdMiddleware.php(32): Laminas\Stratigility\Next->handle()
#64 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): PhpMiddleware\RequestId\RequestIdMiddleware->process()
#65 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process()
#66 /var/www/shlink/vendor/shlinkio/shlink-common/src/Middleware/ContentLengthMiddleware.php(24): Laminas\Stratigility\Next->handle()
#67 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Shlinkio\Shlink\Common\Middleware\ContentLengthMiddleware->process()
#68 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process()
#69 /var/www/shlink/vendor/shlinkio/shlink-common/src/Middleware/AccessLogMiddleware.php(26): Laminas\Stratigility\Next->handle()
#70 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Shlinkio\Shlink\Common\Middleware\AccessLogMiddleware->process()
#71 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Mezzio\Middleware\LazyLoadingMiddleware->process()
#72 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#73 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(49): Laminas\Stratigility\MiddlewarePipe->process()
#74 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#75 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(64): Laminas\Stratigility\MiddlewarePipe->process()
#76 /var/www/shlink/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(73): Laminas\Stratigility\MiddlewarePipe->handle()
#77 /var/www/shlink/vendor/mezzio/mezzio/src/Application.php(53): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#78 /var/www/shlink/config/run.php(13): Mezzio\Application->run()
#79 /var/www/shlink/public/index.php(5): {closure}()
#80 {main}
```

### Expected behavior

No errors occur

### Minimum steps to reproduce

upgrade from 3.4.0 -> 3.5.0

**Comment by theofficialgman** [comment]
Seems related to https://github.com/shlinkio/shlink/issues/1684#issuecomment-1408490333 but with a different database type.

**Comment by theofficialgman** [comment]
Also related to https://github.com/shlinkio/shlink/discussions/1862#discussioncomment-6835822

It seems that shlink is not clearing the apcu cache on upgrade (redis is not used by me). Can this be accomplished manually as a workaround so I can upgrade?

**Comment by theofficialgman** [comment]
> Do you have other running Shlink instances in the same server? From older versions?

No. Only one running instance at once. I always stop the nginx server before attempting the upgrade.

Executing `/etc/init.d/php8.1-fpm restart` cleared the cache and worked around the issue.
