### ISSUE TITLE
Using redis as pub/sub

### ISSUE THREAD

**Issue by brunoguidone** [shlinkio/shlink#2202]
### Shlink version

4.2.0

### PHP version

4.2.0

### How do you serve Shlink

Docker image

### Database engine

PostgreSQL

### Database version

16

### Current behavior

Hello

We are trying to use Redis as pubsub but getting an error on startup. 
Also the channels in Redis are empty, tried to subscribe with redis-cli to check.

OUT  Fatal error: Uncaught Error: Cannot use object of type Predis\Response\Error as array in /etc/shlink/vendor/symfony/cache/Traits/RedisTrait.php:518
2024-10-04T01:20:10.310236243Z   OUT  Stack trace:
2024-10-04T01:20:10.310239672Z   OUT  #0 /etc/shlink/vendor/symfony/cache/Traits/AbstractAdapterTrait.php(133): Symfony\Component\Cache\Adapter\RedisAdapter->doClear('Shlink:')
2024-10-04T01:20:10.310242743Z   OUT  #1 /etc/shlink/vendor/doctrine/orm/src/Tools/Console/Command/ClearCache/MetadataCommand.php(45): Symfony\Component\Cache\Adapter\AbstractAdapter->clear()
2024-10-04T01:20:10.310247092Z   OUT  #2 /etc/shlink/vendor/symfony/console/Command/Command.php(279): Doctrine\ORM\Tools\Console\Command\ClearCache\MetadataCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2024-10-04T01:20:10.310251652Z   OUT  #3 /etc/shlink/vendor/symfony/console/Application.php(1029): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2024-10-04T01:20:10.310255263Z   OUT  #4 /etc/shlink/vendor/symfony/console/Application.php(316): Symfony\Component\Console\Application->doRunCommand(Object(Doctrine\ORM\Tools\Console\Command\ClearCache\MetadataCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2024-10-04T01:20:10.310258183Z   OUT  #5 /etc/shlink/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

We couldn't find the channel names in documentation as well.

We are using environment variables to configure the container in Kubernetes using the latest oficial image.

Could you please give us any advise ?

thank you!

### Expected behavior

Should be able to get messages in Redis channels

### Minimum steps to reproduce

- Start a docker container or in kubernetes using Redis environment variables
- Start a docker container running the latest redis version.
- Try to generate an event to publish in Redis

**Comment by acelaya** [comment]
Could you provide a minimal docker-compose config where this can be reproduced consistently?

**Comment by acelaya** [comment]
Closing as not reproducible. I'm happy to reopen if a minimum environment is provided.

**Comment by acelaya** [comment]
This issue was reported in https://github.com/shlinkio/shlink/issues/2244 with more information to reproduce the issue.

You can find further details of the investigation there.
