### ISSUE TITLE
TypeError: Doctrine\ORM\Mapping\DefaultQuoteStrategy::getColumnName(): Return value must be of type string

### ISSUE THREAD

**Issue by liferadioat** [shlinkio/shlink#2209]
### Shlink version

4.2.1

### PHP version

8.2.24

### How do you serve Shlink

Self-hosted nginx

### Database engine

MariaDB

### Database version

10.6.19

### Current behavior

After upgrading to version 4.2.0 the app server doesn´t work (Something went wrong while loading short URLs :( ). Error log at data/log:
```
[2024-10-07T08:17:01.385450+00:00] [cf5fb78c-8299-46fb-af25-55668e4ae890] Shlink.ERROR - TypeError: Doctrine\ORM\Mapping\DefaultQuoteStrategy::getColumnName(): Return value must be of type string, null returned in /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/doctrine/orm/src/Mapping/DefaultQuoteStrategy.php:28
Stack trace:
#0 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/doctrine/orm/src/Persisters/Entity/BasicEntityPersister.php(1674): Doctrine\ORM\Mapping\DefaultQuoteStrategy->getColumnName()
#1 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/doctrine/orm/src/Persisters/Entity/BasicEntityPersister.php(1595): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->getSelectConditionStatementColumnSQL()
#2 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/doctrine/orm/src/Persisters/Entity/BasicEntityPersister.php(1744): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->getSelectConditionStatementSQL()
#3 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/doctrine/orm/src/Persisters/Entity/BasicEntityPersister.php(1106): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->getSelectConditionSQL()
#4 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/doctrine/orm/src/Persisters/Entity/BasicEntityPersister.php(732): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->getSelectSQL()
#5 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/doctrine/orm/src/EntityRepository.php(125): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load()
#6 /srv/customers/liferadio/websites/shortener/htdocs/shlink/module/Rest/src/Service/ApiKeyService.php(73): Doctrine\ORM\EntityRepository->findOneBy()
#7 /srv/customers/liferadio/websites/shortener/htdocs/shlink/module/Rest/src/Service/ApiKeyService.php(40): Shlinkio\Shlink\Rest\Service\ApiKeyService->getByKey()
#8 /srv/customers/liferadio/websites/shortener/htdocs/shlink/module/Rest/src/Middleware/AuthenticationMiddleware.php(47): Shlinkio\Shlink\Rest\Service\ApiKeyService->check()
#9 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Shlinkio\Shlink\Rest\Middleware\AuthenticationMiddleware->process()
#10 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(52): Mezzio\Middleware\LazyLoadingMiddleware->process()
#11 /srv/customers/liferadio/websites/shortener/htdocs/shlink/module/Rest/src/Middleware/BodyParserMiddleware.php(34): Laminas\Stratigility\Next->handle()
#12 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Shlinkio\Shlink\Rest\Middleware\BodyParserMiddleware->process()
#13 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(52): Mezzio\Middleware\LazyLoadingMiddleware->process()
#14 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/mezzio/mezzio-router/src/Middleware/ImplicitOptionsMiddleware.php(75): Laminas\Stratigility\Next->handle()
#15 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Mezzio\Router\Middleware\ImplicitOptionsMiddleware->process()
#16 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(52): Mezzio\Middleware\LazyLoadingMiddleware->process()
#17 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(77): Laminas\Stratigility\Next->handle()
#18 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Middleware/PathMiddlewareDecorator.php(60): Laminas\Stratigility\MiddlewarePipe->process()
#19 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(52): Laminas\Stratigility\Middleware\PathMiddlewareDecorator->process()
#20 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(45): Laminas\Stratigility\Next->handle()
#21 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/mezzio/mezzio-router/src/Middleware/ImplicitHeadMiddleware.php(77): Laminas\Stratigility\Next->handle()
#22 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Mezzio\Router\Middleware\ImplicitHeadMiddleware->process()
#23 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(52): Mezzio\Middleware\LazyLoadingMiddleware->process()
#24 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/mezzio/mezzio-router/src/Middleware/RouteMiddleware.php(50): Laminas\Stratigility\Next->handle()
#25 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Mezzio\Router\Middleware\RouteMiddleware->process()
#26 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(52): Mezzio\Middleware\LazyLoadingMiddleware->process()
#27 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(77): Laminas\Stratigility\Next->handle()
#28 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(52): Laminas\Stratigility\MiddlewarePipe->process()
#29 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(45): Laminas\Stratigility\Next->handle()
#30 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/shlinkio/shlink-common/src/Middleware/CloseDbConnectionMiddleware.php(24): Laminas\Stratigility\Next->handle()
#31 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Shlinkio\Shlink\Common\Middleware\CloseDbConnectionMiddleware->process()
#32 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(52): Mezzio\Middleware\LazyLoadingMiddleware->process()
#33 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(77): Laminas\Stratigility\Next->handle()
#34 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(52): Laminas\Stratigility\MiddlewarePipe->process()
#35 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Middleware/PathMiddlewareDecorator.php(122): Laminas\Stratigility\Next->handle()
#36 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#37 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/mezzio/mezzio-problem-details/src/ProblemDetailsMiddleware.php(46): Laminas\Stratigility\Next->handle()
#38 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Mezzio\ProblemDetails\ProblemDetailsMiddleware->process()
#39 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(52): Mezzio\Middleware\LazyLoadingMiddleware->process()
#40 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(77): Laminas\Stratigility\Next->handle()
#41 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Middleware/PathMiddlewareDecorator.php(60): Laminas\Stratigility\MiddlewarePipe->process()
#42 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(52): Laminas\Stratigility\Middleware\PathMiddlewareDecorator->process()
#43 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(45): Laminas\Stratigility\Next->handle()
#44 /srv/customers/liferadio/websites/shortener/htdocs/shlink/module/Rest/src/Middleware/CrossDomainMiddleware.php(24): Laminas\Stratigility\Next->handle()
#45 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Shlinkio\Shlink\Rest\Middleware\CrossDomainMiddleware->process()
#46 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(52): Mezzio\Middleware\LazyLoadingMiddleware->process()
#47 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Middleware/ErrorHandler.php(129): Laminas\Stratigility\Next->handle()
#48 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Laminas\Stratigility\Middleware\ErrorHandler->process()
#49 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(52): Mezzio\Middleware\LazyLoadingMiddleware->process()
#50 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/shlinkio/shlink-common/src/Middleware/RequestIdMiddleware.php(33): Laminas\Stratigility\Next->handle()
#51 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Shlinkio\Shlink\Common\Middleware\RequestIdMiddleware->process()
#52 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(52): Mezzio\Middleware\LazyLoadingMiddleware->process()
#53 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/shlinkio/shlink-common/src/Middleware/ContentLengthMiddleware.php(16): Laminas\Stratigility\Next->handle()
#54 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Shlinkio\Shlink\Common\Middleware\ContentLengthMiddleware->process()
#55 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(52): Mezzio\Middleware\LazyLoadingMiddleware->process()
#56 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/shlinkio/shlink-common/src/Middleware/AccessLogMiddleware.php(26): Laminas\Stratigility\Next->handle()
#57 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(26): Shlinkio\Shlink\Common\Middleware\AccessLogMiddleware->process()
#58 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(52): Mezzio\Middleware\LazyLoadingMiddleware->process()
#59 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(77): Laminas\Stratigility\Next->handle()
#60 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/Next.php(52): Laminas\Stratigility\MiddlewarePipe->process()
#61 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(77): Laminas\Stratigility\Next->handle()
#62 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(66): Laminas\Stratigility\MiddlewarePipe->process()
#63 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(73): Laminas\Stratigility\MiddlewarePipe->handle()
#64 /srv/customers/liferadio/websites/shortener/htdocs/shlink/vendor/mezzio/mezzio/src/Application.php(53): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#65 /srv/customers/liferadio/websites/shortener/htdocs/shlink/config/run.php(13): Mezzio\Application->run()
#66 /srv/customers/liferadio/websites/shortener/htdocs/shlink/public/index.php(5): {closure}()
#67 {main}
```

### Expected behavior

Working after the upgrade.

### Minimum steps to reproduce

Upgrade from 3.6 to 4.2. at php8.2 with `sudo -u shortener php8.2 vendor/bin/shlink-installer update`

**Comment by liferadioat** [comment]
Restart of php-fpm and nginx did the trick.
