### ISSUE TITLE
docker failiure

### ISSUE THREAD

**Issue by chovy** [shlinkio/shlink#740]
```
( ! ) Fatal error: Uncaught LogicException: The specified directory path "/home/shlink/module/Core/config/../templates" does not exist. in /home/shlink/www/vendor/league/plates/src/Template/Folder.php:72 Stack trace: #0 /home/shlink/www/vendor/league/plates/src/Template/Folder.php(39): League\Plates\Template\Folder->setPath('/home/shlink/mo...') #1 /home/shlink/www/vendor/league/plates/src/Template/Folders.php(31): League\Plates\Template\Folder->__construct('ShlinkCore', '/home/shlink/mo...', true) #2 /home/shlink/www/vendor/league/plates/src/Engine.php(115): League\Plates\Template\Folders->add('ShlinkCore', '/home/shlink/mo...', true) #3 /home/shlink/www/vendor/mezzio/mezzio-platesrenderer/src/PlatesRenderer.php(78): League\Plates\Engine->addFolder('ShlinkCore', '/home/shlink/mo...', true) #4 /home/shlink/www/vendor/mezzio/mezzio-platesrenderer/src/PlatesRendererFactory.php(64): Mezzio\Plates\PlatesRenderer->addPath('/home/shlink/mo...', 'ShlinkCore') #5 /home/shlink/www/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(765): Mezzio\Plates\PlatesRendererFactory->__invoke(Object(Laminas\ServiceManager\ServiceManager), 'Mezzio\\Plates\\P...', NULL) #6 /home/shlink/www/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(201): Laminas\ServiceManager\ServiceManager->doCreate('Mezzio\\Plates\\P...') #7 /home/shlink/www/vendor/mezzio/mezzio/src/Container/ServerRequestErrorResponseGeneratorFactory.php(26): Laminas\ServiceManager\ServiceManager->get('Mezzio\\Plates\\P...') #8 /home/shlink/www/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(765): Mezzio\Container\ServerRequestErrorResponseGeneratorFactory->__invoke(Object(Laminas\ServiceManager\ServiceManager), 'Mezzio\\Response...', NULL) #9 /home/shlink/www/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(201): Laminas\ServiceManager\ServiceManager->doCreate('Mezzio\\Response...') #10 /home/shlink/www/vendor/mezzio/mezzio-swoole/src/SwooleRequestHandlerRunnerFactory.php(39): Laminas\ServiceManager\ServiceManager->get('Mezzio\\Response...') #11 /home/shlink/www/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(765): Mezzio\Swoole\SwooleRequestHandlerRunnerFactory->__invoke(Object(Laminas\ServiceManager\ServiceManager), 'Mezzio\\Swoole\\S...', NULL) #12 /home/shlink/www/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(201): Laminas\ServiceManager\ServiceManager->doCreate('Mezzio\\Swoole\\S...') #13 /home/shlink/www/vendor/mezzio/mezzio/src/Container/ApplicationFactory.php(40): Laminas\ServiceManager\ServiceManager->get('Mezzio\\Swoole\\S...') #14 /home/shlink/www/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(704): Mezzio\Container\ApplicationFactory->__invoke(Object(Laminas\ServiceManager\ServiceManager), 'Mezzio\\Applicat...', NULL) #15 /home/shlink/www/vendor/mezzio/mezzio/src/Container/ApplicationConfigInjectionDelegator.php(43): Laminas\ServiceManager\ServiceManager->Laminas\ServiceManager\{closure}() #16 /home/shlink/www/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(739): Mezzio\Container\ApplicationConfigInjectionDelegator->__invoke(Object(Laminas\ServiceManager\ServiceManager), 'Mezzio\\Applicat...', Object(Closure), NULL) #17 /home/shlink/www/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(743): Laminas\ServiceManager\ServiceManager->Laminas\ServiceManager\{closure}(Object(Laminas\ServiceManager\ServiceManager), 'Mezzio\\Applicat...', Object(Closure), NULL) #18 /home/shlink/www/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(767): Laminas\ServiceManager\ServiceManager->createDelegatorFromName('Mezzio\\Applicat...', NULL) #19 /home/shlink/www/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(201): Laminas\ServiceManager\ServiceManager->doCreate('Mezzio\\Applicat...') #20 /home/shlink/www/config/run.php(12): Laminas\ServiceManager\ServiceManager->get('Mezzio\\Applicat...') #21 /home/shlink/www/public/index.php(6): {closure}() #22 {main} Next Laminas\ServiceManager\Exception\ServiceNotCreatedException: Service with name "Mezzio\Plates\PlatesRenderer" could not be created. Reason: The specified directory path "/home/shlink/module/Core/config/../templates" does not exist. in /home/shlink/www/vendor/laminas/laminas-servicemanager/src/ServiceManager.php on line 772
--


```

**Comment by acelaya** [comment]
Closing this, as it's impossible to reproduce with such little information.

Please, on future issues, make sure to fill in all the information requested in the issue template. It's there for a reason.

**Comment by chovy** [comment]
this project sucks.
