### ISSUE TITLE
Unable to create SVG QR code - Class 'SimpleXMLElement' not found

### ISSUE THREAD

**Issue by codaamok** [shlinkio/shlink#970]
#### How Shlink is set-up

* Shlink Version: 2.5.0
* PHP Version: 7.4.14
* How do you serve Shlink: |Self-hosted nginx
* Database engine used: MariaDB 15.1

#### Summary

I'm having difficulty creating an SVG shortcode in 2.5.0.

I'm not sure if this a problem with the URI I'm creating, but are you able to successfully create an SVG QR code from API? I'm getting an error 500 code from my web server and having a hard time troubleshooting it.

I am using the content type header `accept: image/svg+xml` in my GET request. PNG works fine.

A `data/log` file prints with the below when I make a request for SVG.

```
[2021-01-18T22:58:48.102913+00:00] [NULL] Shlink.ERROR - Error: Class 'SimpleXMLElement' not found in /var/www/shlink/vendor/endroid/qr-code/src/Writer/SvgWriter.php:32
Stack trace:
#0 /var/www/shlink/vendor/endroid/qr-code/src/QrCode.php(397): Endroid\QrCode\Writer\SvgWriter->writeString()
#1 /var/www/shlink/vendor/shlinkio/shlink-common/src/Response/QrCodeResponse.php(29): Endroid\QrCode\QrCode->writeString()
#2 /var/www/shlink/vendor/shlinkio/shlink-common/src/Response/QrCodeResponse.php(20): Shlinkio\Shlink\Common\Response\QrCodeResponse->createBody()
#3 /var/www/shlink/module/Core/src/Action/QrCodeAction.php(64): Shlinkio\Shlink\Common\Response\QrCodeResponse->__construct()
#4 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Shlinkio\Shlink\Core\Action\QrCodeAction->process()
#5 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process()
#6 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#7 /var/www/shlink/vendor/mezzio/mezzio-router/src/Route.php(91): Laminas\Stratigility\MiddlewarePipe->process()
#8 /var/www/shlink/vendor/mezzio/mezzio-router/src/RouteResult.php(103): Mezzio\Router\Route->process()
#9 /var/www/shlink/vendor/mezzio/mezzio-router/src/Middleware/DispatchMiddleware.php(36): Mezzio\Router\RouteResult->process()
#10 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Mezzio\Router\Middleware\DispatchMiddleware->process()
#11 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process()
#12 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#13 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\MiddlewarePipe->process()
#14 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Middleware/PathMiddlewareDecorator.php(48): Laminas\Stratigility\Next->handle()
#15 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\PathMiddlewareDecorator->process()
#16 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(54): Laminas\Stratigility\Next->handle()
#17 /var/www/shlink/vendor/mezzio/mezzio-router/src/Middleware/ImplicitHeadMiddleware.php(82): Laminas\Stratigility\Next->handle()
#18 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Mezzio\Router\Middleware\ImplicitHeadMiddleware->process()
#19 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process()
#20 /var/www/shlink/vendor/mezzio/mezzio-router/src/Middleware/RouteMiddleware.php(56): Laminas\Stratigility\Next->handle()
#21 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Mezzio\Router\Middleware\RouteMiddleware->process()
#22 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process()
#23 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#24 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\MiddlewarePipe->process()
#25 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(54): Laminas\Stratigility\Next->handle()
#26 /var/www/shlink/vendor/shlinkio/shlink-common/src/Middleware/CloseDbConnectionMiddleware.php(27): Laminas\Stratigility\Next->handle()
#27 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Shlinkio\Shlink\Common\Middleware\CloseDbConnectionMiddleware->process()
#28 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process()
#29 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#30 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\MiddlewarePipe->process()
#31 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Middleware/PathMiddlewareDecorator.php(48): Laminas\Stratigility\Next->handle()
#32 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\PathMiddlewareDecorator->process()
#33 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(54): Laminas\Stratigility\Next->handle()
#34 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Middleware/ErrorHandler.php(144): Laminas\Stratigility\Next->handle()
#35 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Laminas\Stratigility\Middleware\ErrorHandler->process()
#36 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process()
#37 /var/www/shlink/vendor/mezzio/mezzio-helpers/src/ContentLengthMiddleware.php(32): Laminas\Stratigility\Next->handle()
#38 /var/www/shlink/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php(47): Mezzio\Helper\ContentLengthMiddleware->process()
#39 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Mezzio\Middleware\LazyLoadingMiddleware->process()
#40 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#41 /var/www/shlink/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\MiddlewarePipe->process()
#42 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#43 /var/www/shlink/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73): Laminas\Stratigility\MiddlewarePipe->process()
#44 /var/www/shlink/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#45 /var/www/shlink/vendor/mezzio/mezzio/src/Application.php(82): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#46 /var/www/shlink/config/run.php(14): Mezzio\Application->run()
#47 /var/www/shlink/public/index.php(6): {closure}()
#48 {main}
```

**Comment by acelaya** [comment]
That's because the xml extension is needed.

I forgot to document this when I added support for SVG QR codes.
